[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"
VITE_APP_ENV = "production"
VITE_API_BASE_URL = "https://site.api.espn.com/apis"
VITE_OPENWEATHER_API_KEY = "${OPENWEATHER_API_KEY}"
VITE_FEATURE_DEBUG_MODE = "false" 