[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "docker build --build-arg VITE_OPENWEATHER_API_KEY=$VITE_OPENWEATHER_API_KEY --build-arg VITE_APP_ENV=$VITE_APP_ENV --build-arg VITE_APP_URL=$VITE_APP_URL --build-arg VITE_API_BASE_URL=$VITE_API_BASE_URL --build-arg VITE_FEATURE_DEBUG_MODE=$VITE_FEATURE_DEBUG_MODE -t app ."

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"
VITE_APP_ENV = "production"
VITE_API_BASE_URL = "https://site.api.espn.com/apis"
VITE_OPENWEATHER_API_KEY = "${OPENWEATHER_API_KEY}"
VITE_FEATURE_DEBUG_MODE = "false" 