[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"  # Production port only 